set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'   # save pane content

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'                  # auto-restore on tmux start
set -g @continuum-save-interval '5'            # save every 5 mins (default is 15)

set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# TODO - Get things from this and disable plugin
# set -g @plugin 'tmux-plugins/tmux-sensible'

# inspiration https://raine.dev/blog/my-tmux-setup/
# https://old.reddit.com/r/Ghostty/comments/1hoi3id/my_perfect_ghostty_tmux_nvim_configuration_on/

# Set scrollback limit
set-option -g history-limit 50000

# proper terminal colors
set -g default-terminal "tmux-256color"

# - From oh-my-tmux start

setw -g aggressive-resize on         # Aggressive resize for shared sessions

# status bar top
set -g status-position top
# Set the background colour to red: 
set -g status-style bg=red
# Change the text on the right to the time only: 
set -g status-right '%H:%M'
# Underline the current window
set -g window-status-current-style 'underscore'

set -g set-titles on          # set terminal title

set -g display-panes-time 800 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time

set -g status-interval 10     # redraw status line every 10 seconds

# activity
set -g monitor-activity on
set -g visual-activity off

# - From oh-my-tmux end

# Enable mouse support
set -g mouse on

# don't exit from tmux when closing a session
set -g detach-on-destroy off

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Pane cycling
bind O select-pane -t :.-
bind P select-pane -t :.+ 
bind n next-window
bind p previous-window

bind k display-popup -h 90% -w 50% -E "sesh picker -i"

# Move window to the left
bind -n M-i swap-window -t -1

# Move window to the right
bind -n M-o swap-window -t +1

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Change prefix key to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

run '~/.config/tmux/plugins/tpm/tpm'
