set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'   # save pane content

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'                  # auto-restore on tmux start
set -g @continuum-save-interval '5'            # save every 5 mins (default is 15)

# set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

### Status Bar
set -g @plugin 'fabioluciano/tmux-powerkit'

# Basic configuration
set -g @powerkit_plugins ""

# Theme
set -g @powerkit_theme "flexoki"
set -g @powerkit_theme_variant "dark"

# Configure separator style
set -g @powerkit_separator_style "pixel"
# Different style for edge separators
set -g @powerkit_edge_separator_style "slantup"
# Add spacing between elements
set -g @powerkit_elements_spacing "windows"  # false, true, both, windows, plugins

# Customize update interval
set -g @powerkit_status_interval "5"
# Make it transparent
set -g @powerkit_transparent "true"

# inspiration https://raine.dev/blog/my-tmux-setup/
# https://old.reddit.com/r/Ghostty/comments/1hoi3id/my_perfect_ghostty_tmux_nvim_configuration_on/

# Set scrollback limit
set-option -g history-limit 50000

# proper terminal colors
set -g default-terminal "tmux-256color"

# - From oh-my-tmux start

setw -g aggressive-resize on         # Aggressive resize for shared sessions

# Enable mouse support
set -g mouse on

# don't exit from tmux when closing a session
set -g detach-on-destroy off

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Pane cycling
bind O select-pane -t :.-
bind P select-pane -t :.+ 
bind n next-window
bind p previous-window

bind-key x kill-pane # kill without prompting

bind k display-popup -h 90% -w 50% -E "sesh picker -i"

# Move window to the left
bind -n M-i swap-window -t -1

# Move window to the right
bind -n M-o swap-window -t +1

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Change prefix key to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

run '~/.config/tmux/plugins/tpm/tpm'
